### ISSUE TITLE
Container for ARM

### ISSUE THREAD

**Issue by lordot** [tazihad/byedpi-docker#2]
I hava a mikrotik router. Could you make an ARM image for it?

**Comment by tazihad** [comment]
please test and let me know if arm is working. use the `test` tag.
```
tazihad/byedpi:test
```

**Comment by flar4eg** [comment]
![изображение_2024-08-05_203536935](https://github.com/user-attachments/assets/f38a8063-9344-4637-b1f5-a27cb1a010e5)
Not work whith mikrotik.

**Comment by lordot** [comment]
Have you made it for arm64 or arm32? Need arm32

**Comment by tazihad** [comment]
@lordot I just pushed for arm/v7 and arm64 please check and let me know. it's with the `test` tag. `tazihad/byedpi:test`

**Comment by lordot** [comment]
@tazihad Thx! Now it works. Could you make some normal tag for it please? 
![image](https://github.com/user-attachments/assets/e6f69861-5196-4258-bd6a-480c0c60a590)

**Comment by tazihad** [comment]
@lordot use the `latest` one. I pushed it.
